services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client-server-api
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306